name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Force npm update
      run: |
        npm install -g npm@11.1.0
        npm config set fund false
        npm config set audit false

    - name: Clean install dependencies
      run: |
        # Remove old lockfile if exists
        rm -f package-lock.json
        # Install exact TypeScript version required by react-scripts
        npm install typescript@4.9.5 --save-exact
        # Install remaining dependencies with forced resolution
        npm install --legacy-peer-deps --force

    - name: Build project
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Verify installations
      run: |
        npm list typescript
        npm list react-scripts
